### ISSUE TITLE
[fixed]not working

### ISSUE THREAD

**Issue by saeedyp** [The-LoneWolf/AndroPress#2]
stocks at loading
here is the log

10-16 10:25:45.003 7899-7899/? I/art: Not late-enabling -Xcheck:jni (already on)
10-16 10:25:45.003 7899-7899/? W/art: Unexpected CPU variant for X86 using defaults: x86_64
10-16 10:25:45.137 7899-7899/ir.technopedia.wordpressjsonclient W/System: ClassLoader referenced unknown path: /data/app/ir.technopedia.wordpressjsonclient-1/lib/x86_64
10-16 10:25:45.157 7899-7899/ir.technopedia.wordpressjsonclient I/InstantRun: Instant Run Runtime started. Android package is ir.technopedia.wordpressjsonclient, real application class is null.
10-16 10:25:47.143 7899-7899/ir.technopedia.wordpressjsonclient W/System: ClassLoader referenced unknown path: /data/app/ir.technopedia.wordpressjsonclient-1/lib/x86_64
10-16 10:25:47.237 7899-7899/ir.technopedia.wordpressjsonclient W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
10-16 10:25:47.482 7899-7899/ir.technopedia.wordpressjsonclient D/NetworkSecurityConfig: No Network Security Config specified, using platform default
10-16 10:25:47.567 7899-7899/ir.technopedia.wordpressjsonclient W/gralloc_ranchu: Gralloc pipe failed

```
                                                                              [ 10-16 10:25:47.568  7899: 7899 D/         ]
                                                                              HostConnection::get() New Host Connection established 0x7ffef370e7a0, tid 7899
```

10-16 10:25:47.655 7899-7963/ir.technopedia.wordpressjsonclient I/OpenGLRenderer: Initialized EGL, version 1.4
10-16 10:25:47.655 7899-7963/ir.technopedia.wordpressjsonclient D/OpenGLRenderer: Swap behavior 1
10-16 10:25:49.582 7899-7899/ir.technopedia.wordpressjsonclient V/AsyncHttpRH: Progress 4096 from 1 (409600%)
10-16 10:25:49.583 7899-7899/ir.technopedia.wordpressjsonclient V/AsyncHttpRH: Progress 7977 from 1 (797700%)
10-16 10:25:49.583 7899-7899/ir.technopedia.wordpressjsonclient V/AsyncHttpRH: Progress 12073 from 1 (1207300%)
10-16 10:25:49.583 7899-7899/ir.technopedia.wordpressjsonclient V/AsyncHttpRH: Progress 16169 from 1 (1616900%)
10-16 10:25:49.583 7899-7899/ir.technopedia.wordpressjsonclient V/AsyncHttpRH: Progress 18492 from 1 (1849200%)
10-16 10:25:49.621 7899-7899/ir.technopedia.wordpressjsonclient W/JsonHttpRH: onFailure(int, Header[], String, Throwable) was not overriden, but callback was received
                                                                              org.json.JSONException: Response cannot be parsed as JSON data
                                                                                  at com.loopj.android.http.JsonHttpResponseHandler$1$1.run(JsonHttpResponseHandler.java:158)
                                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
10-16 10:25:49.646 7899-7899/ir.technopedia.wordpressjsonclient V/AsyncHttpRH: Progress 4096 from 1 (409600%)
10-16 10:25:49.646 7899-7899/ir.technopedia.wordpressjsonclient V/AsyncHttpRH: Progress 7977 from 1 (797700%)
10-16 10:25:49.647 7899-7899/ir.technopedia.wordpressjsonclient V/AsyncHttpRH: Progress 12073 from 1 (1207300%)
10-16 10:25:49.651 7899-7899/ir.technopedia.wordpressjsonclient V/AsyncHttpRH: Progress 16169 from 1 (1616900%)
10-16 10:25:49.654 7899-7899/ir.technopedia.wordpressjsonclient V/AsyncHttpRH: Progress 18492 from 1 (1849200%)
10-16 10:25:49.699 7899-7899/ir.technopedia.wordpressjsonclient W/JsonHttpRH: onFailure(int, Header[], String, Throwable) was not overriden, but callback was received
                                                                              org.json.JSONException: Response cannot be parsed as JSON data
                                                                                  at com.loopj.android.http.JsonHttpResponseHandler$1$1.run(JsonHttpResponseHandler.java:158)
                                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by The-LoneWolf** [comment]
please give me the line you have set value to variable base url in android? there should be something wrong with address you've entered because this code is tested on 3 different wordpress blogs and works correctly

**Comment by saeedyp** [comment]
this my api address 
http://danesh-file.ir/api

**Comment by The-LoneWolf** [comment]
you see the problem is that :)
you are missing a / at the end
the address should be like

http://danesh-file.ir/api/

**Comment by saeedyp** [comment]
:)))
thanks alot
